# Generated by Django 3.2.7 on 2023-03-05 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0002_alter_property_tax'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='property',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(default=0, verbose_name='Number of floors'),
        ),
        migrations.AlterField(
            model_name='property',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Agent, seller or buyer'),
        ),
    ]
