# Generated by Django 3.2.7 on 2023-03-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(default='Say something about yourself', verbose_name='About_me'),
        ),
    ]
